### ISSUE TITLE
Current release is broken

### ISSUE THREAD

**Issue by mikhailtchernychev** [barsnick/valkyrie#3]
Hi,
First of all thank you very much for keeping this project alive. There are only few GUIs for valgrind, some of them heavy (like eclipse)  other alternative is codeblocks.

Unfortunately current release is broken.

In files vglogreader.h and cpp you cannot drop "unused" argument in startElement()

The declaration and implementation should be

bool startElement( const QString& nsURI,
                       const QString& localName,
                       const QString& qName,
                       const QXmlAttributes& atts );

Even QXmlAttributes& atts argument is not used in your implementation signature must match 
one in the base class QXmlDeafultHandler, because this function is virtual.  
There is more modern keyword "override" which could be used in .h files and allows
compiler to catch this.

Adding const QXmlAttributes& atts to function declaration and implementation fixes the issue.

Thank you again,
Mikhail

**Comment by barsnick** [comment]
Thanks for your reports.

Please note that I am not maintaining this project, I am just making sure it can still compile (and probably work) in modern environments.

Please be a bit more clear what you mean with broken.
- Does it not compile, or does it compile with warnings?
- Does it crash at runtime?
- Does it not work as expected, and how?

From your description, I understand that the implementation of `VgLogHandler::startElement()` does not match with the virtual function `QXmlDefaultHandler::startElement()` to override. Did you get a warning? I would have expected something like
```
warning: ‘virtual bool QXmlDefaultHandler::startElement()’ was hidden [-Woverloaded-virtual=]
```
(which I do get for `QXmlSimpleReader::parse()`.

Functionally, it shouldn't matter, because Qt6 docs say
> This reimplementation does nothing.

I hope that valkyrie works nevertheless. What is your experience?

I'll try to fix this and the warning about `VgLogReader::parse()`.

**Comment by mikhailtchernychev** [comment]
I should be more specific. Program compiled, but not working as expected. It was not able to parse valgrind XML file, and therefore was not usable.  Not sure there could be compiler warning because new signature means new function is defined which is perfectly fine in C++ I have to admit I did not watch compile log closely.
I compiled and ran latest version and it works.
Thank you for fixing this.

**Comment by barsnick** [comment]
Okay, thanks!

Does valkyrie now work for you with these changes?

I got this with the memcheck test program, so it seems to be working:
![Screenshot from 2024-09-24 12-52-13](https://github.com/user-attachments/assets/2c7c7915-5c13-4f47-ab61-de4cbd81df01)

**Comment by mikhailtchernychev** [comment]
Yes it is working. Thank you very much!
You can close the ticket or I can close whatever you prefer. 
Thanks again,
Mikhail

**Comment by barsnick** [comment]
Thanks for your feedback!

**Comment by mikhailtchernychev** [comment]
Oh, thank you for keeping this alive.

Best Regards, Mikhail
 

    On Friday, September 27, 2024 at 03:19:23 AM PDT, barsnick ***@***.***> wrote:  
 
 


Thanks for your feedback!
